### ISSUE TITLE
Remove Mcrypt dependency

### ISSUE THREAD

**Issue by ada-lambrecht** [OvRcode/ovr_lists#1]
Lists is still running on a php 5.x server. The login system uses a PBKDF2 implementation that uses mcrypt. Login/Registration needs to be re-written/updated to use Argon2/Libsodium instead of deprecated functions.

**Comment by barnardm** [comment]
Fixing this will allow lists to be upgraded to php 7.x

**Comment by ada-lambrecht** [comment]
solved. found a mcrypt compatibility shim file and set it up. Will replace login system in the future
